
 const SongsData = [
  {
    id: '1',
    singerName: 'Celine Dion',
    title: 'Power of love',
    style: 'slow',
    lyrics: '',
    upVotes: 50,
    downVotes: 30,
    isFavorite: false,
  },
  {
    id: '2',
    singerName: 'Black nadia',
    title: 'Mizara karatse',
    style: 'slow',
    lyrics: '',
    upVotes: 70,
    downVotes: 10,
    isFavorite: false,
  },
  {
    id: '3',
    singerName: 'Tinah',
    title: 'sefo',
    style: 'Salegy',
    lyrics: '',
    upVotes: 50,
    downVotes: 20,
    isFavorite: false,
  },
  {
    id: '4',
    singerName: 'Tsiliva',
    title: 'Ambanimbany',
    style: 'Kilalaky',
    lyrics: '',
    upVotes: 30,
    downVotes: 30,
    isFavorite: false,
  },
  {
    id: '5',
    singerName: 'Master KG',
    title: 'Jerosalum',
    style: 'slow',
    lyrics: '',
    upVotes: 12,
    downVotes: 30,
    isFavorite: false,
  },
  {
    id: '6',
    singerName: 'Andress',
    title: 'Tsy ariak',
    style: 'salegy',
    lyrics: '',
    upVotes: 30,
    downVotes: 19,
    isFavorite: false,
  },
  {
    id: '7',
    singerName: 'WaWa',
    title: 'Misy misoma ratsy',
    style: 'Kawitry',
    lyrics: '',
    upVotes: 90,
    downVotes: 40,
    isFavorite: false,
  },
  {
    id: '8',
    singerName: 'Stephanie',
    title: 'Iha malay aho io',
    style: 'slow',
    lyrics: '',
    upVotes: 30,
    downVotes: 10,
    isFavorite: false,
  },
  {
    id: '9',
    singerName: 'Ljo',
    title: 'Vady',
    style: 'Rnb',
    lyrics: '',
    upVotes: 50,
    downVotes: 20,
    isFavorite: false,
  },
  {
    id: '10',
    singerName: 'Mad max',
    title: 'olo jiaby',
    style: 'Danseall',
    lyrics: '',
    upVotes: 30,
    downVotes: 20,
    isFavorite: false,
  },

]

export default SongsData;
